language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
before_install:
- cp test-$PLONE_VERSION.x.cfg buildout.cfg
install:
- python bootstrap.py
- bin/buildout -N annotate
- bin/buildout -N
script:
# - bin/code-analysis
- bin/test
