language: python
python: 2.7
sudo: false
env:
  - PLONE_VERSION=5.x
cache:
  pip: true
  directories:
    - $HOME/eggs
matrix:
  fast_finish: true
before_install:
  - virtualenv .
  - bin/pip install --upgrade zc.buildout==2.8.0 setuptools==34.1.1
  - cp test-$PLONE_VERSION.cfg buildout.cfg
install:
  - bin/buildout -N -t 3 annotate
  - bin/buildout -N -t 3
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
